/*********************************************************************
 * File Name: http_print.c
 *
 * Provides callback headers and resolution for user's custom
 * HTTP Application.
 * 
 * This file is automatically generated by the MPFS Utility
 * ALL MODIFICATIONS WILL BE OVERWRITTEN BY THE MPFS GENERATOR
 *
 * Software License Agreement
 *
 * Copyright (C) 2012 Microchip Technology Inc.  All rights
 * reserved.
 * Microchip licenses to you the right to use, modify, copy, and distribute
 * software only embedded on a Microchip microcontroller or digital signal 
 * controller that is integrated into your product or third party product
 * (pursuant to the sublicense terms in the accompanying license agreement)

 * You should refer to the license agreement accompanying this 
 * Software for additional information regarding your rights and 
 * obligations.
 *
 * You should refer to the license agreement accompanying this 
 * Software for additional information regarding your rights and 
 * obligations.
 *
 * THE SOFTWARE AND DOCUMENTATION ARE PROVIDED "AS IS" WITHOUT
 * WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT
 * LIMITATION, ANY WARRANTY OF MERCHANTABILITY, FITNESS FOR A 
 * PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL
 * MICROCHIP BE LIABLE FOR ANY INCIDENTAL, SPECIAL, INDIRECT OR
 * CONSEQUENTIAL DAMAGES, LOST PROFITS OR LOST DATA, COST OF
 * PROCUREMENT OF SUBSTITUTE GOODS, TECHNOLOGY OR SERVICES, ANY CLAIMS
 * BY THIRD PARTIES (INCLUDING BUT NOT LIMITED TO ANY DEFENSE 
 * THEREOF), ANY CLAIMS FOR INDEMNITY OR CONTRIBUTION, OR OTHER 
 * SIMILAR COSTS, WHETHER ASSERTED ON THE BASIS OF CONTRACT, TORT
 * (INCLUDING NEGLIGENCE), BREACH OF WARRANTY, OR OTHERWISE.
 *
 *********************************************************************/

#include "tcpip/tcpip.h"

void TCPIP_HTTP_Print(HTTP_CONN_HANDLE connHandle,uint32_t callbackID);
void TCPIP_HTTP_Print_config_ip(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_config_gw(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_config_subnet(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_config_dns1(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_config_name(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_config_NTP(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_config_ver(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_EEPROM(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_uploadedmd5(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_stateBackup(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_Config_rte_dst1(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_Config_rte_mask1(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_Config_rte_interface1(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_Config_rte_dst2(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_Config_rte_mask2(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_Config_rte_interface2(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_Config_rte_dst3(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_Config_rte_mask3(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_Config_rte_interface3(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_Config_rte_dst4(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_Config_rte_mask4(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_Config_rte_interface4(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_stateBackupPopup(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_BCKUP_Ready(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_AudioOutSelect(HTTP_CONN_HANDLE connHandle,uint16_t);
void TCPIP_HTTP_Print_ValV(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_ValB(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_ValA(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_OVB(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_OVA(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_VolO(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_Balance(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_Name_Config(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_Checked(HTTP_CONN_HANDLE connHandle,uint16_t);
void TCPIP_HTTP_Print_Config_Defaut(HTTP_CONN_HANDLE connHandle,uint16_t);
void TCPIP_HTTP_Print_disabled(HTTP_CONN_HANDLE connHandle,uint16_t);
void TCPIP_HTTP_Print_ConfigCSV(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_hiddenMasterGain(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_MasterGainChecked(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_MasterGainTxt(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_TxtGainOut(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_PT(HTTP_CONN_HANDLE connHandle,uint16_t);
void TCPIP_HTTP_Print_AD(HTTP_CONN_HANDLE connHandle,uint16_t);
void TCPIP_HTTP_Print_CacheModeUsine(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_hiddenReduction(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_value_Overload1(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_Detection_Muting1(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_Time_Muting1(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_value_Overload2(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_Detection_Muting2(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_Time_Muting2(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_cacheMiddle(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_ValC(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_ValueReduction(HTTP_CONN_HANDLE connHandle);
void TCPIP_HTTP_Print_Select(HTTP_CONN_HANDLE connHandle,uint16_t);
void TCPIP_HTTP_Print_footer(HTTP_CONN_HANDLE connHandle);

void TCPIP_HTTP_Print(HTTP_CONN_HANDLE connHandle,uint32_t callbackID)
{
    TCP_SOCKET sktHTTP; 
    switch(callbackID)
    {
        case 0x00000000:
			TCPIP_HTTP_FileInclude(connHandle,(const uint8_t *)"header.inc");
			break;
        case 0x000000d5:
			TCPIP_HTTP_Print_config_ip(connHandle);
			break;
        case 0x000000d6:
			TCPIP_HTTP_Print_config_gw(connHandle);
			break;
        case 0x000000d7:
			TCPIP_HTTP_Print_config_subnet(connHandle);
			break;
        case 0x000000d8:
			TCPIP_HTTP_Print_config_dns1(connHandle);
			break;
        case 0x000000fd:
			TCPIP_HTTP_Print_config_name(connHandle);
			break;
        case 0x000000fe:
			TCPIP_HTTP_Print_config_NTP(connHandle);
			break;
        case 0x000000ff:
			TCPIP_HTTP_Print_config_ver(connHandle);
			break;
        case 0x00000100:
			TCPIP_HTTP_Print_EEPROM(connHandle);
			break;
        case 0x00000101:
			TCPIP_HTTP_Print_uploadedmd5(connHandle);
			break;
        case 0x00000105:
			TCPIP_HTTP_Print_stateBackup(connHandle);
			break;
        case 0x00000120:
			TCPIP_HTTP_Print_Config_rte_dst1(connHandle);
			break;
        case 0x00000121:
			TCPIP_HTTP_Print_Config_rte_mask1(connHandle);
			break;
        case 0x00000122:
			TCPIP_HTTP_Print_Config_rte_interface1(connHandle);
			break;
        case 0x00000123:
			TCPIP_HTTP_Print_Config_rte_dst2(connHandle);
			break;
        case 0x00000124:
			TCPIP_HTTP_Print_Config_rte_mask2(connHandle);
			break;
        case 0x00000125:
			TCPIP_HTTP_Print_Config_rte_interface2(connHandle);
			break;
        case 0x00000126:
			TCPIP_HTTP_Print_Config_rte_dst3(connHandle);
			break;
        case 0x00000127:
			TCPIP_HTTP_Print_Config_rte_mask3(connHandle);
			break;
        case 0x00000128:
			TCPIP_HTTP_Print_Config_rte_interface3(connHandle);
			break;
        case 0x00000129:
			TCPIP_HTTP_Print_Config_rte_dst4(connHandle);
			break;
        case 0x0000012a:
			TCPIP_HTTP_Print_Config_rte_mask4(connHandle);
			break;
        case 0x0000012b:
			TCPIP_HTTP_Print_Config_rte_interface4(connHandle);
			break;
        case 0x000001d2:
			TCPIP_HTTP_Print_stateBackupPopup(connHandle);
			break;
        case 0x000001d3:
			TCPIP_HTTP_Print_BCKUP_Ready(connHandle);
			break;
        case 0x000001ec:
			TCPIP_HTTP_Print_AudioOutSelect(connHandle,1);
			break;
        case 0x000001ed:
			TCPIP_HTTP_Print_AudioOutSelect(connHandle,2);
			break;
        case 0x000001ee:
			TCPIP_HTTP_Print_AudioOutSelect(connHandle,3);
			break;
        case 0x000001ef:
			TCPIP_HTTP_Print_AudioOutSelect(connHandle,4);
			break;
        case 0x000001f0:
			TCPIP_HTTP_Print_AudioOutSelect(connHandle,5);
			break;
        case 0x000001f1:
			TCPIP_HTTP_Print_AudioOutSelect(connHandle,6);
			break;
        case 0x000001f2:
			TCPIP_HTTP_Print_AudioOutSelect(connHandle,7);
			break;
        case 0x00000200:
			TCPIP_HTTP_Print_AudioOutSelect(connHandle,0);
			break;
        case 0x00000202:
			TCPIP_HTTP_Print_ValV(connHandle);
			break;
        case 0x00000205:
			TCPIP_HTTP_Print_ValB(connHandle);
			break;
        case 0x00000206:
			TCPIP_HTTP_Print_ValA(connHandle);
			break;
        case 0x0000020b:
			TCPIP_HTTP_Print_OVB(connHandle);
			break;
        case 0x0000020c:
			TCPIP_HTTP_Print_OVA(connHandle);
			break;
        case 0x00000231:
			TCPIP_HTTP_Print_VolO(connHandle);
			break;
        case 0x00000235:
			TCPIP_HTTP_Print_Balance(connHandle);
			break;
        case 0x00000240:
			TCPIP_HTTP_Print_Name_Config(connHandle);
			break;
        case 0x00000247:
			TCPIP_HTTP_Print_Checked(connHandle,0);
			break;
        case 0x00000248:
			TCPIP_HTTP_Print_Checked(connHandle,1);
			break;
        case 0x00000249:
			TCPIP_HTTP_Print_Checked(connHandle,2);
			break;
        case 0x0000024a:
			TCPIP_HTTP_Print_Checked(connHandle,3);
			break;
        case 0x0000024b:
			TCPIP_HTTP_Print_Checked(connHandle,4);
			break;
        case 0x0000024c:
			TCPIP_HTTP_Print_Config_Defaut(connHandle,0);
			break;
        case 0x0000024d:
			TCPIP_HTTP_Print_disabled(connHandle,0);
			break;
        case 0x0000024e:
			TCPIP_HTTP_Print_Config_Defaut(connHandle,1);
			break;
        case 0x0000024f:
			TCPIP_HTTP_Print_disabled(connHandle,1);
			break;
        case 0x00000250:
			TCPIP_HTTP_Print_Config_Defaut(connHandle,2);
			break;
        case 0x00000251:
			TCPIP_HTTP_Print_disabled(connHandle,2);
			break;
        case 0x00000252:
			TCPIP_HTTP_Print_Config_Defaut(connHandle,3);
			break;
        case 0x00000253:
			TCPIP_HTTP_Print_disabled(connHandle,3);
			break;
        case 0x00000254:
			TCPIP_HTTP_Print_Config_Defaut(connHandle,4);
			break;
        case 0x00000255:
			TCPIP_HTTP_Print_disabled(connHandle,4);
			break;
        case 0x00000261:
			TCPIP_HTTP_Print_ConfigCSV(connHandle);
			break;
        case 0x00000262:
			TCPIP_HTTP_Print_hiddenMasterGain(connHandle);
			break;
        case 0x00000263:
			TCPIP_HTTP_Print_MasterGainChecked(connHandle);
			break;
        case 0x00000264:
			TCPIP_HTTP_Print_MasterGainTxt(connHandle);
			break;
        case 0x00000266:
			TCPIP_HTTP_Print_TxtGainOut(connHandle);
			break;
        case 0x0000026f:
			TCPIP_HTTP_Print_PT(connHandle,0);
			break;
        case 0x00000270:
			TCPIP_HTTP_Print_PT(connHandle,1);
			break;
        case 0x00000271:
			TCPIP_HTTP_Print_PT(connHandle,2);
			break;
        case 0x00000272:
			TCPIP_HTTP_Print_PT(connHandle,3);
			break;
        case 0x00000273:
			TCPIP_HTTP_Print_PT(connHandle,4);
			break;
        case 0x00000274:
			TCPIP_HTTP_Print_PT(connHandle,5);
			break;
        case 0x00000275:
			TCPIP_HTTP_Print_PT(connHandle,6);
			break;
        case 0x00000276:
			TCPIP_HTTP_Print_PT(connHandle,7);
			break;
        case 0x00000277:
			TCPIP_HTTP_Print_PT(connHandle,8);
			break;
        case 0x00000278:
			TCPIP_HTTP_Print_PT(connHandle,9);
			break;
        case 0x00000279:
			TCPIP_HTTP_Print_PT(connHandle,10);
			break;
        case 0x0000027a:
			TCPIP_HTTP_Print_PT(connHandle,11);
			break;
        case 0x0000027b:
			TCPIP_HTTP_Print_PT(connHandle,12);
			break;
        case 0x0000027c:
			TCPIP_HTTP_Print_AD(connHandle,0);
			break;
        case 0x0000027d:
			TCPIP_HTTP_Print_AD(connHandle,1);
			break;
        case 0x0000027e:
			TCPIP_HTTP_Print_AD(connHandle,2);
			break;
        case 0x0000027f:
			TCPIP_HTTP_Print_AD(connHandle,3);
			break;
        case 0x00000283:
			TCPIP_HTTP_Print_CacheModeUsine(connHandle);
			break;
        case 0x00000284:
			TCPIP_HTTP_Print_hiddenReduction(connHandle);
			break;
        case 0x00000297:
			TCPIP_HTTP_Print_value_Overload1(connHandle);
			break;
        case 0x00000298:
			TCPIP_HTTP_Print_Detection_Muting1(connHandle);
			break;
        case 0x00000299:
			TCPIP_HTTP_Print_Time_Muting1(connHandle);
			break;
        case 0x0000029a:
			TCPIP_HTTP_Print_value_Overload2(connHandle);
			break;
        case 0x0000029b:
			TCPIP_HTTP_Print_Detection_Muting2(connHandle);
			break;
        case 0x0000029c:
			TCPIP_HTTP_Print_Time_Muting2(connHandle);
			break;
        case 0x0000029d:
			TCPIP_HTTP_Print_cacheMiddle(connHandle);
			break;
        case 0x0000029e:
			TCPIP_HTTP_Print_ValC(connHandle);
			break;
        case 0x0000029f:
			TCPIP_HTTP_Print_ValueReduction(connHandle);
			break;
        case 0x000002a0:
			TCPIP_HTTP_Print_Select(connHandle,0);
			break;
        case 0x000002a1:
			TCPIP_HTTP_Print_Select(connHandle,1);
			break;
        case 0x000002a2:
			TCPIP_HTTP_Print_Select(connHandle,2);
			break;
        case 0x000002a3:
			TCPIP_HTTP_Print_Select(connHandle,3);
			break;
        case 0x000002a4:
			TCPIP_HTTP_Print_Select(connHandle,4);
			break;
        case 0x000002a5:
			TCPIP_HTTP_Print_Select(connHandle,5);
			break;
        case 0x000002a6:
			TCPIP_HTTP_Print_Select(connHandle,6);
			break;
        case 0x000002a7:
			TCPIP_HTTP_Print_footer(connHandle);
			break;
        default:
            // Output notification for undefined values
            sktHTTP = TCPIP_HTTP_CurrentConnectionSocketGet(connHandle);
            TCPIP_TCP_ArrayPut(sktHTTP, (const uint8_t *)"!DEF", 4);
    }
    return;
}

void TCPIP_HTTP_Print_myVariable(HTTP_CONN_HANDLE connHandle)
{
    TCP_SOCKET sktHTTP = TCPIP_HTTP_CurrentConnectionSocketGet(connHandle);
    TCPIP_TCP_Put(sktHTTP, '~');
    return;
}
