<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd" Cache-Control:public;>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta charset="utf-8" />

<title>RadioBox</title>
<link href="/mchp.css" rel="stylesheet" type="text/css" />
<script src="/mchp.js" type="text/javascript"></script>
</head>

<body onload="showTime();">
<div id="shadow-one"><div id="shadow-two"><div id="shadow-three"><div id="shadow-four">
<div id="page">

<div style="padding:0 0 75px 0px"><div id="img_left" ><img src="/Logo_Swoxtelecom.jpg" alt="Logo_Swoxtelecom"/> </div>
<div id="img_right"><img src="/Logo_SWISSDAB.png" alt="Logo_SWISSDAB"/></div></div>

<div id="title">
	<div class = "right">Management ID unit</div>

	<div "left"  id="theDate" > </div>

</div>

<ul id="menu">
	<li><a href="/Input_Audio.htm">Audio In</a></li>
	<li><a href="/Output_Audio.htm">Audio Out</a></li>
	<li><a href="/Options.htm">Options</a></li>
	<li><a href="/Test_Upload.htm">Select Config</a></li>
	<li><a href="/maintenance/network.htm">Maintenance</a>
		<ul>
			<li><a href="/maintenance/network.htm">Network</a></li>
			<li><a href="/maintenance/routes.htm">Routing table</a></li>
			<li><a href="/maintenance/monitoring.htm">Monitoring</a></li>			
			<li><a href="/maintenance/boot.htm">Bootloader</a></li>
		</ul>
	</li>
</ul>


